#!/usr/bin/perl
# This script requires libintl-perl(>=0.90).
use Locale::TextDomain ("frames.texi" => "TITLES/");
my ($en, $ja);
while (<>) {
	($en, $ja) = (quotemeta('@chapter Frames'), __ '@chapter Frames'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Creating Frames'), __ '@section Creating Frames'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Multiple Terminals'), __ '@section Multiple Terminals'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Frame Geometry'), __ '@section Frame Geometry'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Frame Layout'), __ '@subsection Frame Layout'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Frame Font'), __ '@subsection Frame Font'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Frame Position'), __ '@subsection Frame Position'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Frame Size'), __ '@subsection Frame Size'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Implied Frame Resizing'), __ '@subsection Implied Frame Resizing'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Frame Parameters'), __ '@section Frame Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Access to Frame Parameters'), __ '@subsection Access to Frame Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Initial Frame Parameters'), __ '@subsection Initial Frame Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Window Frame Parameters'), __ '@subsection Window Frame Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Basic Parameters'), __ '@subsubsection Basic Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Position Parameters'), __ '@subsubsection Position Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Size Parameters'), __ '@subsubsection Size Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Layout Parameters'), __ '@subsubsection Layout Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Buffer Parameters'), __ '@subsubsection Buffer Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Frame Interaction Parameters'), __ '@subsubsection Frame Interaction Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Mouse Dragging Parameters'), __ '@subsubsection Mouse Dragging Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Window Management Parameters'), __ '@subsubsection Window Management Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Cursor Parameters'), __ '@subsubsection Cursor Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Font and Color Parameters'), __ '@subsubsection Font and Color Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Geometry'), __ '@subsection Geometry'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Terminal Parameters'), __ '@section Terminal Parameters'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Frame Titles'), __ '@section Frame Titles'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Deleting Frames'), __ '@section Deleting Frames'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Finding All Frames'), __ '@section Finding All Frames'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Minibuffers and Frames'), __ '@section Minibuffers and Frames'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Input Focus'), __ '@section Input Focus'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Visibility of Frames'), __ '@section Visibility of Frames'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Raising, Lowering and Restacking Frames'), __ '@section Raising, Lowering and Restacking Frames'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Frame Configurations'), __ '@section Frame Configurations'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Child Frames'), __ '@section Child Frames'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Mouse Tracking'), __ '@section Mouse Tracking'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Mouse Position'), __ '@section Mouse Position'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Pop-Up Menus'), __ '@section Pop-Up Menus'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Dialog Boxes'), __ '@section Dialog Boxes'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Pointer Shape'), __ '@section Pointer Shape'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Window System Selections'), __ '@section Window System Selections'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Drag and Drop'), __ '@section Drag and Drop'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Color Names'), __ '@section Color Names'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Text Terminal Colors'), __ '@section Text Terminal Colors'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section X Resources'), __ '@section X Resources'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Display Feature Testing'), __ '@section Display Feature Testing'); s/$en/$ja/;
	print;
}
